<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/*
 * S02 — Database & Persistence Foundation.
 *
 * Enables btree_gist, the only PostgreSQL extension MasarHR requires.
 *
 * Why: temporal integrity is enforced with GiST exclusion constraints of the form
 *   EXCLUDE USING gist (owner_id WITH =, daterange(effective_from, effective_to, '[)') WITH &&)
 * A GiST index has no equality operator class for uuid (or other scalar) columns by itself;
 * btree_gist provides it, which is what allows "WITH =" on the owner column.
 *
 * Deliberately NOT enabled: uuid-ossp and pgcrypto. UUIDs are generated by the application
 * (UUIDv7) with gen_random_uuid() — built into PostgreSQL core since 13 — as the database default.
 *
 * btree_gist is a "trusted" extension (PostgreSQL 13+), so a non-superuser role that owns the
 * database can install it. Idempotent: safe to re-run. Rollback is RESTRICT-only: it fails if any
 * index or constraint still depends on the extension.
 */
return new class extends Migration
{
    public function up(): void
    {
        $this->assertPostgreSql();

        DB::statement('CREATE EXTENSION IF NOT EXISTS btree_gist');
    }

    public function down(): void
    {
        $this->assertPostgreSql();

        DB::statement('DROP EXTENSION IF EXISTS btree_gist RESTRICT');
    }

    private function assertPostgreSql(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            throw new RuntimeException('MasarHR migrations require PostgreSQL; refusing to run on another driver.');
        }
    }
};
